/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
https://projecteuler.net/problem=2
 */

package solutions.Q1to9;

import java.util.stream.Stream;

public class Problem2 {
	public static void main(String[] args) {
		System.out.println(fibSum());
	}
	
	public static long fibSum(){
		return Stream.iterate(new long[]{1, 1}, e -> new long[] { e[1], e[0]+e[1]})
					 .limit(92)
				     .mapToLong(e -> e[0])
				     .filter(e -> e < 4000000)
				     .filter(e -> (e % 2 == 0))
				     .sum();				     
	}
}
